const rotacionMapasArray = [
  "monkey_l",
  "raiden5",
  "shutdown2",
  "phantom",
  "siege",
  "fry_baked_lg",
  "siden",
  "hellion",
  "alchimy_l2",
  "destroy_l",
  "high_flag",
  "mortality_l",
  "openfire_lowgrens",
  "oppose2k1_lowgrens",
  "orbit_l3",
  "prolifique",
  "schtop",
  "ss_nyx_ectfc",
  "voltage_l",
  "waterwar",
  "2fort",
  "chimkey_l",
  "bases2k4",
  "2mesa3",
  "decay_l",
  "tempest_r3",
  "stowaway2",
  "crossover2",
  "congestus",
  "bluetopia",
  "opposition2"
]; //Rotacion de mapas

exports.rotacionMapasArray = rotacionMapasArray