const rotacionMapasArray = [
  "turbo_10b",
  "datchurch",
  "goldcoast",
  "monkey_l",
  "raiden5",
  "serenity_r",
  "shutdown2",
  "phantom",
  "siege",
  "fry_baked_lg",
  "siden",
  "hellion",
  "alchimy_l2",
  "destroy_l",
  "high_flag",
  "mortality_l",
  "openfire_lowgrens",
  "orbit_l3",
  "prolifique",
  "schtop",
  "ss_nyx_ectfc",
  "voltage_l",
  "waterwar",
  "2fort",
  "chimkey_l",
  "2mesa3",
  "stowaway2",
  "blutopia",
  "mulch_trench_lg",
  "chaos2_b2",
]; //Rotacion de mapas

exports.rotacionMapasArray = rotacionMapasArray